version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '8.12'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            - run: npm test
            - run: |
                if [ "$CIRCLE_BRANCH" == "master" ] && [ "$CD_SKIP" != "1" ]; then
                    ./publish.sh
                fi
workflows:
    build-and-test:
      jobs:
        - build-and-test
