version: 2.1
jobs:
    build:
        machine:
            docker_layer_caching: true
        resource_class: large
        working_directory: ~/repo
        steps:
            - checkout
            - run: |
                  if [ "$CIRCLE_BRANCH" != "master" ]; then
                    ./cd.sh
                    circleci-agent step halt
                  fi
            - run: ./ci.sh
            - run: |
                if [ "$CD_SKIP" == "1" ]; then
                    circleci-agent step halt
                fi
