version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '14.15'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            - run: npm run lint
            - run: npm test
            - run: npm --version
            - run: |
                if [ "$CIRCLE_BRANCH" == "master" ] && [ "$CD_SKIP" != "1" ]; then
                    ./publish.sh
                fi
workflows:
    build-and-test:
      jobs:
        - build-and-test
