version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build-test-deploy:
    executor:
      name: node/default
      tag: '16.14.2'
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run lint
      - run: npm test
      - run: node --version
      - run: |
          if [ "$CIRCLE_BRANCH" == "main" ] && [ "$CD_SKIP" != "1" ]; then
              ./publish.sh
          fi

workflows:
    build-and-test:
      jobs:
        - build-test-deploy
